import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

import type { Metadata } from "next";
import { Iceland, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/component/Nav";
import AudioPlayer from "@/component/AudioPlayer";
import { AudioProvider } from "@/context/AudioContext";

const iceland = Iceland({
    variable: "--font-iceland-sans",
    subsets: ["latin"],
    weight: ["400"],
});

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${iceland.variable} ${robotoMono.variable}`}>
            <body>
                <Nav />
                <AudioProvider>
                    {children}
                    <AudioPlayer />
                </AudioProvider>
            </body>
        </html>
    );
}
